/// What a pedal does. Declaration order follows a conventional signal chain,
/// so iterating the enum gives a sensible default ordering in pickers.
enum PedalCategory {
  tuner,
  compressor,
  equalizer,
  boost,
  overdrive,
  distortion,
  fuzz,
  noiseGate,
  modulation,
  chorus,
  flanger,
  phaser,
  tremolo,
  delay,
  reverb,
  ampSim,
  cabinetIr,
  multiEffects,
  looper,
  utility,
  other;

  String get label => switch (this) {
    PedalCategory.tuner => 'Tuner',
    PedalCategory.compressor => 'Compressor',
    PedalCategory.equalizer => 'EQ',
    PedalCategory.boost => 'Boost',
    PedalCategory.overdrive => 'Overdrive',
    PedalCategory.distortion => 'Distortion',
    PedalCategory.fuzz => 'Fuzz',
    PedalCategory.noiseGate => 'Noise Gate',
    PedalCategory.modulation => 'Modulation',
    PedalCategory.chorus => 'Chorus',
    PedalCategory.flanger => 'Flanger',
    PedalCategory.phaser => 'Phaser',
    PedalCategory.tremolo => 'Tremolo',
    PedalCategory.delay => 'Delay',
    PedalCategory.reverb => 'Reverb',
    PedalCategory.ampSim => 'Amp Sim',
    PedalCategory.cabinetIr => 'Cab / IR',
    PedalCategory.multiEffects => 'Multi Effects',
    PedalCategory.looper => 'Looper',
    PedalCategory.utility => 'Utility',
    PedalCategory.other => 'Other',
  };
}
